server:
  port: ${DISPATCHER_PORT:8084}
  ssl:
    enabled: false

bot:
  name: ${TG_BOT_NAME:file_hosting_telegram_bot}
  token: ${TG_BOT_TOKEN:7210054109:AAGGEWpCHyNBK__jnObakCQ6fpd29XGoxjM}
  uri: ${TG_BOT_URI:https://de7e-178-65-130-12.ngrok-free.app}
spring:
  kafka:
    doc_message: ${KAFKA_DOC_MESSAGE}
    photo_message: ${KAFKA_PHOTO_MESSAGE}
    text_message: ${KAFKA_TEXT_MESSAGE:text_message}
    answer_message: ${KAFKA_ANSWER_MESSAGE:answer_message}