server:
  port: ${MAIL_SERVICE_PORT:8087}

spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:465}
    protocol: ${MAIL_PROTOCOL:smtps}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

service:
  activation:
    uri: ${ACTIVATION_URI}

kafka:
  registration_message: ${KAFKA_REGISTRATION_MESSAGE}