server:
  port: 8087

spring:
  mail:
    host: "smtp.yandex.ru"
    port: 465
    protocol: "smtps"
    username: "telegram-mail-service@yandex.ru"
    password: "ncooyjfwvcmeckje"

service:
  activation:
    uri: "http://127.0.0.1:8086/mail/activation?id={id}"