server:
  port: 8085

kafka:
  doc_message: "doc_message"
  photo_message: "photo_message"
  text_message: "text_message"
  answer_message: "answer_message"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres
    generate-ddl: true