server:
  port: ${NODE_PORT:8085}

kafka:
  doc_message: ${KAFKA_DOC_MESSAGE}
  photo_message: ${KAFKA_PHOTO_MESSAGE}
  text_message: ${KAFKA_TEXT_MESSAGE}
  answer_message: ${KAFKA_ANSWER_MESSAGE}
  registration_message: ${KAFKA_REGISTRATION_MESSAGE}

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/test_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  liquibase:
    change-log: ${CHANGE_LOG:classpath:db/changelog/master.yml}
    enabled: true

bot:
  token: ${TG_BOT_TOKEN}
  file_info_uri: ${TG_BOT_FILE_INFO_URI}
  file_storage_uri: ${TG_BOT_FILE_STORAGE_URI}
  linkAddress: ${TG_BOT_URI:127.0.0.1:8086}

hash:
  salt: ${SALT}
  minHashLength: ${MIN_HASH_LENGTH:10}