server:
  port: 8084
  ssl:
    enabled: false

bot:
  name: file_hosting_telegram_bot
  token: 7210054109:AAGGEWpCHyNBK__jnObakCQ6fpd29XGoxjM
  uri: https://bdfb-92-100-102-74.ngrok-free.app

kafka:
  doc_message: doc_message
  photo_message: photo_message
  text_message: text_message
  answer_message: answer_message