server:
  port: 8084

bot:
  name: file_hosting_telegram_bot
  token: 7210054109:AAGGEWpCHyNBK__jnObakCQ6fpd29XGoxjM

kafka:
  doc_message: "doc_message"
  photo_message: "photo_message"
  text_message: "text_message"
  answer_message: "answer_message"