server:
  port: ${REST_SERVICE_PORT:8086}

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/test_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

decoder:
  salt: ${SALT}
  minHashLength: ${MIN_HASH_LENGTH:10}