server:
  port: 8085

kafka:
  doc_message: "doc_message"
  photo_message: "photo_message"
  text_message: "text_message"
  answer_message: "answer_message"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
bot:
  token: 7210054109:AAGGEWpCHyNBK__jnObakCQ6fpd29XGoxjM
  file_info_uri: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
  file_storage_uri: https://api.telegram.org/file/bot{token}/{filePath}
  linkAddress: 127.0.0.1:8086
  mail_uri: http://127.0.0.1:8087/mail/send

hash:
  salt: gKkCxjMgxK
  minHashLength: 10